#include "status.h"

#include "../backend/kb.h"

#include <stddef.h>

NTSTATUS tw_nt_from_kb(int64_t e, int ctx)
{
    if (e >= 0) return STATUS_SUCCESS;
    switch (e) {
    case TW_KB_ENOSYS: return STATUS_NOT_IMPLEMENTED;
    case TW_KB_EFAULT:
        /* A range the kernel will not touch. For VM calls on a range that
         * is not (entirely) one reservation, NT reports the address. */
        return ctx == TW_KBC_VM ? STATUS_MEMORY_NOT_ALLOCATED : STATUS_ACCESS_VIOLATION;
    case TW_KB_EINVAL: return STATUS_INVALID_PARAMETER;
    case TW_KB_ENOMEM:
        return ctx == TW_KBC_HANDLE || ctx == TW_KBC_CREATE ? STATUS_INSUFFICIENT_RESOURCES : STATUS_NO_MEMORY;
    case TW_KB_EBADH:  return STATUS_INVALID_HANDLE;
    case TW_KB_EPERM:  return STATUS_ACCESS_DENIED;
    case TW_KB_EAGAIN: return STATUS_INSUFFICIENT_RESOURCES;
    case TW_KB_ESTATE: return ctx == TW_KBC_VM ? STATUS_CONFLICTING_ADDRESSES : STATUS_INVALID_PARAMETER;
    case TW_KB_ENOENT: return STATUS_OBJECT_NAME_NOT_FOUND;
    case TW_KB_EEXIST: return STATUS_OBJECT_NAME_COLLISION;
    case TW_KB_EACCES: return STATUS_ACCESS_DENIED;
    case TW_KB_EISDIR: return STATUS_FILE_IS_A_DIRECTORY;
    case TW_KB_ENOTDIR: return STATUS_OBJECT_PATH_NOT_FOUND;
    case TW_KB_ELOOP:  return STATUS_OBJECT_PATH_NOT_FOUND;
    case TW_KB_ENOTEMPTY: return STATUS_DIRECTORY_NOT_EMPTY;
    case TW_KB_EIO:    return STATUS_UNSUCCESSFUL;
    default:           return STATUS_UNSUCCESSFUL;
    }
}

struct map { NTSTATUS st; uint32_t win; const char *name; };

/* Win32 codes per [MS-ERREF] and the documented RtlNtStatusToDosError
 * correspondences for the statuses TweakWin produces. */
static const struct map k_map[] = {
    { STATUS_SUCCESS, 0, "STATUS_SUCCESS" },
    { STATUS_TIMEOUT, 1460 /* ERROR_TIMEOUT */, "STATUS_TIMEOUT" },
    { STATUS_PENDING, 997 /* ERROR_IO_PENDING */, "STATUS_PENDING" },
    { STATUS_BUFFER_OVERFLOW, 234 /* ERROR_MORE_DATA */, "STATUS_BUFFER_OVERFLOW" },
    { STATUS_NO_MORE_FILES, 18, "STATUS_NO_MORE_FILES" },
    { STATUS_NO_MORE_ENTRIES, 259, "STATUS_NO_MORE_ENTRIES" },
    { STATUS_BREAKPOINT, 0x80000003u, "STATUS_BREAKPOINT" },
    { STATUS_SINGLE_STEP, 0x80000004u, "STATUS_SINGLE_STEP" },
    { STATUS_GUARD_PAGE_VIOLATION, 0x80000001u, "STATUS_GUARD_PAGE_VIOLATION" },
    { STATUS_DATATYPE_MISALIGNMENT, 998, "STATUS_DATATYPE_MISALIGNMENT" },
    { STATUS_UNSUCCESSFUL, 31 /* ERROR_GEN_FAILURE */, "STATUS_UNSUCCESSFUL" },
    { STATUS_NOT_IMPLEMENTED, 1 /* ERROR_INVALID_FUNCTION */, "STATUS_NOT_IMPLEMENTED" },
    { STATUS_INVALID_INFO_CLASS, 87, "STATUS_INVALID_INFO_CLASS" },
    { STATUS_INFO_LENGTH_MISMATCH, 24 /* ERROR_BAD_LENGTH */, "STATUS_INFO_LENGTH_MISMATCH" },
    { STATUS_ACCESS_VIOLATION, 998 /* ERROR_NOACCESS */, "STATUS_ACCESS_VIOLATION" },
    { STATUS_IN_PAGE_ERROR, 999, "STATUS_IN_PAGE_ERROR" },
    { STATUS_INVALID_HANDLE, 6, "STATUS_INVALID_HANDLE" },
    { STATUS_INVALID_PARAMETER, 87, "STATUS_INVALID_PARAMETER" },
    { STATUS_INVALID_PARAMETER_1, 87, "STATUS_INVALID_PARAMETER_1" },
    { STATUS_INVALID_PARAMETER_2, 87, "STATUS_INVALID_PARAMETER_2" },
    { STATUS_INVALID_PARAMETER_3, 87, "STATUS_INVALID_PARAMETER_3" },
    { STATUS_INVALID_PARAMETER_4, 87, "STATUS_INVALID_PARAMETER_4" },
    { STATUS_INVALID_PARAMETER_MIX, 87, "STATUS_INVALID_PARAMETER_MIX" },
    { STATUS_NO_SUCH_FILE, 2, "STATUS_NO_SUCH_FILE" },
    { STATUS_INVALID_DEVICE_REQUEST, 1, "STATUS_INVALID_DEVICE_REQUEST" },
    { STATUS_END_OF_FILE, 38 /* ERROR_HANDLE_EOF */, "STATUS_END_OF_FILE" },
    { STATUS_NO_MEMORY, 8 /* ERROR_NOT_ENOUGH_MEMORY */, "STATUS_NO_MEMORY" },
    { STATUS_CONFLICTING_ADDRESSES, 487 /* ERROR_INVALID_ADDRESS */, "STATUS_CONFLICTING_ADDRESSES" },
    { STATUS_NOT_MAPPED_VIEW, 487, "STATUS_NOT_MAPPED_VIEW" },
    { STATUS_UNABLE_TO_FREE_VM, 87, "STATUS_UNABLE_TO_FREE_VM" },
    { STATUS_ILLEGAL_INSTRUCTION, 0xC000001Du, "STATUS_ILLEGAL_INSTRUCTION" },
    { STATUS_ALREADY_COMMITTED, 487, "STATUS_ALREADY_COMMITTED" },
    { STATUS_ACCESS_DENIED, 5, "STATUS_ACCESS_DENIED" },
    { STATUS_BUFFER_TOO_SMALL, 122 /* ERROR_INSUFFICIENT_BUFFER */, "STATUS_BUFFER_TOO_SMALL" },
    { STATUS_OBJECT_TYPE_MISMATCH, 6, "STATUS_OBJECT_TYPE_MISMATCH" },
    { STATUS_NONCONTINUABLE_EXCEPTION, 0xC0000025u, "STATUS_NONCONTINUABLE_EXCEPTION" },
    { STATUS_INVALID_DISPOSITION, 0xC0000026u, "STATUS_INVALID_DISPOSITION" },
    { STATUS_OBJECT_NAME_INVALID, 123 /* ERROR_INVALID_NAME */, "STATUS_OBJECT_NAME_INVALID" },
    { STATUS_OBJECT_NAME_NOT_FOUND, 2 /* ERROR_FILE_NOT_FOUND */, "STATUS_OBJECT_NAME_NOT_FOUND" },
    { STATUS_OBJECT_NAME_COLLISION, 183 /* ERROR_ALREADY_EXISTS */, "STATUS_OBJECT_NAME_COLLISION" },
    { STATUS_OBJECT_PATH_INVALID, 161 /* ERROR_BAD_PATHNAME */, "STATUS_OBJECT_PATH_INVALID" },
    { STATUS_OBJECT_PATH_NOT_FOUND, 3 /* ERROR_PATH_NOT_FOUND */, "STATUS_OBJECT_PATH_NOT_FOUND" },
    { STATUS_OBJECT_PATH_SYNTAX_BAD, 161, "STATUS_OBJECT_PATH_SYNTAX_BAD" },
    { STATUS_SHARING_VIOLATION, 32, "STATUS_SHARING_VIOLATION" },
    { STATUS_INVALID_PAGE_PROTECTION, 87, "STATUS_INVALID_PAGE_PROTECTION" },
    { STATUS_MUTANT_NOT_OWNED, 288 /* ERROR_NOT_OWNER */, "STATUS_MUTANT_NOT_OWNED" },
    { STATUS_SEMAPHORE_LIMIT_EXCEEDED, 298 /* ERROR_TOO_MANY_POSTS */, "STATUS_SEMAPHORE_LIMIT_EXCEEDED" },
    { STATUS_THREAD_IS_TERMINATING, 5, "STATUS_THREAD_IS_TERMINATING" },
    { STATUS_SECTION_PROTECTION, 87, "STATUS_SECTION_PROTECTION" },
    { STATUS_DELETE_PENDING, 5, "STATUS_DELETE_PENDING" },
    { STATUS_INVALID_IMAGE_FORMAT, 193 /* ERROR_BAD_EXE_FORMAT */, "STATUS_INVALID_IMAGE_FORMAT" },
    { STATUS_INSUFFICIENT_RESOURCES, 1450 /* ERROR_NO_SYSTEM_RESOURCES */, "STATUS_INSUFFICIENT_RESOURCES" },
    { STATUS_FILE_IS_A_DIRECTORY, 5, "STATUS_FILE_IS_A_DIRECTORY" },
    { STATUS_NOT_SUPPORTED, 50 /* ERROR_NOT_SUPPORTED */, "STATUS_NOT_SUPPORTED" },
    { STATUS_MEMORY_NOT_ALLOCATED, 487, "STATUS_MEMORY_NOT_ALLOCATED" },
    { STATUS_INTEGER_DIVIDE_BY_ZERO, 0xC0000094u, "STATUS_INTEGER_DIVIDE_BY_ZERO" },
    { STATUS_INTEGER_OVERFLOW, 534, "STATUS_INTEGER_OVERFLOW" },
    { STATUS_PRIVILEGED_INSTRUCTION, 0xC0000096u, "STATUS_PRIVILEGED_INSTRUCTION" },
    { STATUS_ARRAY_BOUNDS_EXCEEDED, 0xC000008Cu, "STATUS_ARRAY_BOUNDS_EXCEEDED" },
    { STATUS_FLOAT_DENORMAL_OPERAND, 0xC000008Du, "STATUS_FLOAT_DENORMAL_OPERAND" },
    { STATUS_FLOAT_DIVIDE_BY_ZERO, 0xC000008Eu, "STATUS_FLOAT_DIVIDE_BY_ZERO" },
    { STATUS_FLOAT_INEXACT_RESULT, 0xC000008Fu, "STATUS_FLOAT_INEXACT_RESULT" },
    { STATUS_FLOAT_INVALID_OPERATION, 0xC0000090u, "STATUS_FLOAT_INVALID_OPERATION" },
    { STATUS_FLOAT_OVERFLOW, 0xC0000091u, "STATUS_FLOAT_OVERFLOW" },
    { STATUS_FLOAT_STACK_CHECK, 0xC0000092u, "STATUS_FLOAT_STACK_CHECK" },
    { STATUS_FLOAT_UNDERFLOW, 0xC0000093u, "STATUS_FLOAT_UNDERFLOW" },
    { STATUS_DIRECTORY_NOT_EMPTY, 145 /* ERROR_DIR_NOT_EMPTY */, "STATUS_DIRECTORY_NOT_EMPTY" },
    { STATUS_NOT_A_DIRECTORY, 267 /* ERROR_DIRECTORY */, "STATUS_NOT_A_DIRECTORY" },
    { STATUS_PROCESS_IS_TERMINATING, 5, "STATUS_PROCESS_IS_TERMINATING" },
    { STATUS_NAME_TOO_LONG, 206 /* ERROR_FILENAME_EXCED_RANGE */, "STATUS_NAME_TOO_LONG" },
    { STATUS_DLL_NOT_FOUND, 126 /* ERROR_MOD_NOT_FOUND */, "STATUS_DLL_NOT_FOUND" },
    { STATUS_ORDINAL_NOT_FOUND, 182 /* ERROR_INVALID_ORDINAL */, "STATUS_ORDINAL_NOT_FOUND" },
    { STATUS_ENTRYPOINT_NOT_FOUND, 127 /* ERROR_PROC_NOT_FOUND */, "STATUS_ENTRYPOINT_NOT_FOUND" },
    { STATUS_PROCEDURE_NOT_FOUND, 127, "STATUS_PROCEDURE_NOT_FOUND" },
    { STATUS_DLL_INIT_FAILED, 1114 /* ERROR_DLL_INIT_FAILED */, "STATUS_DLL_INIT_FAILED" },
    { STATUS_INVALID_ADDRESS, 487, "STATUS_INVALID_ADDRESS" },
    { STATUS_NO_UNICODE_TRANSLATION, 1113, "STATUS_NO_UNICODE_TRANSLATION" },
    { STATUS_STACK_OVERFLOW, 1001 /* ERROR_STACK_OVERFLOW */, "STATUS_STACK_OVERFLOW" },
    { STATUS_INVALID_CID, 87, "STATUS_INVALID_CID" },
    { STATUS_TOO_MANY_THREADS, 1450, "STATUS_TOO_MANY_THREADS" },
    { STATUS_KEY_DELETED, 1018 /* ERROR_KEY_DELETED */, "STATUS_KEY_DELETED" },
    { STATUS_PIPE_BROKEN, 109 /* ERROR_BROKEN_PIPE */, "STATUS_PIPE_BROKEN" },
    { STATUS_CANCELLED, 995 /* ERROR_OPERATION_ABORTED */, "STATUS_CANCELLED" },
    { STATUS_COMMITMENT_LIMIT, 1455, "STATUS_COMMITMENT_LIMIT" },
    { STATUS_INVALID_VIEW_SIZE, 87, "STATUS_INVALID_VIEW_SIZE" },
    { STATUS_SECTION_TOO_BIG, 87, "STATUS_SECTION_TOO_BIG" },
    { STATUS_OBJECT_NAME_EXISTS, 183, "STATUS_OBJECT_NAME_EXISTS" },
    { STATUS_STACK_BUFFER_OVERRUN, 0xC0000409u, "STATUS_STACK_BUFFER_OVERRUN" },
    { STATUS_HEAP_CORRUPTION, 0xC0000374u, "STATUS_HEAP_CORRUPTION" },
    { STATUS_INVALID_EXCEPTION_HANDLER, 0xC00001A5u, "STATUS_INVALID_EXCEPTION_HANDLER" },
    { STATUS_BAD_STACK, 0xC0000028u, "STATUS_BAD_STACK" },
    { STATUS_INVALID_UNWIND_TARGET, 0xC0000029u, "STATUS_INVALID_UNWIND_TARGET" },
    { STATUS_UNWIND, 0xC0000027u, "STATUS_UNWIND" },
    { STATUS_ABANDONED_WAIT_0, 0, "STATUS_ABANDONED_WAIT_0" },
};

static const struct map *find(NTSTATUS st)
{
    for (size_t i = 0; i < sizeof k_map / sizeof k_map[0]; i++)
        if (k_map[i].st == st) return &k_map[i];
    return NULL;
}

uint32_t tw_nt_to_win32(NTSTATUS st)
{
    const struct map *m = find(st);
    if (m) return m->win;
    /* Success / informational statuses that are not in the table map to
     * ERROR_SUCCESS; anything else is "no mapping" (317). */
    if ((uint32_t)st < 0x40000000u) return 0;
    return 317;
}

const char *tw_nt_status_name(NTSTATUS st)
{
    const struct map *m = find(st);
    return m ? m->name : NULL;
}
